plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/StringLiterals:
  EnforcedStyle: double_quotes
